### ISSUE TITLE
[feature request/enhancement] note creation date in status bar

### ISSUE THREAD

**Issue by SublimeAnanas** [Yustynn/obsidian-last-modified-timestamp-in-status-bar#1]
Most user-made Templater templates contain both the note creation date, as well as the last modified date. It would be awesome if we could replace both of these Templater scripts with this plugin, so I'm proposing an enhancement which displays the note creation date in the status bar as well, with an option to change the date format and another one to turn it off completely if a user does not need it.

**Comment by Yustynn** [comment]
Hey @SublimeAnanas. Yeah makes sense, will add it

**Comment by Yustynn** [comment]
Added in in v1.1.0
