### ISSUE TITLE
[feature request/enhancement] Make refresh interval selectable

### ISSUE THREAD

**Issue by macbikegeek** [Yustynn/obsidian-last-modified-timestamp-in-status-bar#3]
It would be great if the refresh interval could be adjusted. I don't need to know every 2 seconds but some people will want that. I'd like to be able to set the interval to at least several minutes. Nicest if units can be specified but I don't mind doing the math to specify 300 seconds for 5 minutes.

Thanks for considering - this is a great plugin.

**Comment by Yustynn** [comment]
Hey Lee

Yeah was gonna add this in the next update anyway, so no problem

**Comment by macbikegeek** [comment]
Thanks, great minds think alike!

**Comment by Yustynn** [comment]
Added in v1.1.0
