### ISSUE TITLE
FR: Option to turn off one of the timestamps

### ISSUE THREAD

**Issue by Liong1976** [Yustynn/obsidian-last-modified-timestamp-in-status-bar#4]
Hello and thank you for creating this amazing plugin.

I was wondering if there is a way to disable either the Creation or Last Modified timestamps. Personally, I only require the Last Modified timestamp, and having both of them displayed causes my status bar to become too lengthy for my theme and preference.

Thank you for taking my request into consideration.

**Comment by Yustynn** [comment]
Hey @Liong1976 

Sure. Added in v1.2.0. Just update your plugin and you'll get the feature :)

**Comment by Liong1976** [comment]
Thanks, @Yustynn
