### ISSUE TITLE
Automatic install fails (manual succeeds still)

### ISSUE THREAD

**Issue by travisterrell** [Yustynn/obsidian-last-modified-timestamp-in-status-bar#8]
Hi, thanks for creating this plugin. It's a nice, unobtrusive way to see when a file was last edited!

I'm not sure if you'll be interested in digging into this issue or not, since the plugin hasn't been updated in a couple of years, but for what it's worth, I was only able to install it manually (i.e. creating a folder in the .plugins directory & copying the files). When I attempt to use the Install/Update button in Obsidian, I receive a toast notification that says _Failed to install plugin "File Creation and Last Modified Timestamps in Status Bar"_. Unfortunately, I'm not really familiar enough with Obsidian to know how to find a more detailed error message. I can confirm it still works perfectly once installed, though!

Thanks!

**Comment by Yustynn** [comment]
Oh strange, I'll check out what the problem is on the weekend

**Comment by travisterrell** [comment]
Cool! That'll be nice. BTW if there's any troubleshooting you want me to do, I don't mind. Though I imagine you'll have the same issue when you test.
(Edit: oops, accidentally closed it for a second. Reopened now)

**Comment by churnish** [comment]
Same issue here! When I click "Install":

<img width="1029" alt="Screen Shot 2024-10-20 at 19 11 19" src="https://github.com/user-attachments/assets/d631344b-0e93-4d7c-81d2-62cf5bea03f5">

**Comment by Yustynn** [comment]
@travisterrell @greetclammy I've updated it, could you try again?

**Comment by churnish** [comment]
Installed successfully! 🙌
